# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'RemindMe - Track TODOs and FIXMEs as GitHub issues'
author: 'Kevin de Jong'
description: >
  Track TODOs and FIXMEs as GitHub issues.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: false

runs:
  using: 'node16'
  main: 'lib/main/index.js'
